Update 4.3 Tip Selection Algorithm.md
iotaledger/IOTA-2.0-Research-Specifications pull request #65
Opened 2021-06-11 17:35 UTC by darcy-camargo

Basic Standardization procedures, due to June 15th

2021-06-11 17:40 UTC, darcy-camargo commented on 4.3 Tip Selection Algorithm.md
> +-
```suggestion

```

2021-06-23 11:15 UTC, oliviasaa commented on 4.3 Tip Selection Algorithm.md
> +- 5.2 - Ledger State
```suggestion
- [2.2 - Message Layout](./2.2%20Message%20Layout.md)
- [2.4 - Data Flow](./2.4%20Data%20Flow.md)
- [4.1 - The Tangle](./4.1%20The%20Tangle.md)
- [5.2 - Ledger State](./5.2%20Ledger%20State.md)
```

2021-06-23 11:16 UTC, oliviasaa requested changes
missing links

2021-06-27 09:18 UTC, oliviasaa approved these changes

2021-06-27 09:18 UTC, merged