Add manual peering spec
iotaledger/IOTA-2.0-Research-Specifications pull request #84
Opened 2021-07-21 07:28 UTC by jkrvivian

2021-07-28 02:06 UTC, darcy-camargo commented on 3.5 Manual Peering.md
> +A node removes a peer by closing the connection directly without sending a drop message described in [Section 3.4 - Peer Selection](./3.4%20Peer%20Selection.md) to the peer. Thus, the removed peer sh
```suggestion
A node removes a peer by closing the connection directly without sending a drop message described in [Section 3.4 - Peer Selection](./3.4%20Peer%20Selection.md) to the peer. Thus, the removed peer shall still try to reconnect to the node every `reconnectInterval`, until its operator removes the node from the manual peering list. That is, it is the node operators' responsibility to monitor and manage the known peer list in manual peering.
```

2021-07-28 11:56 UTC, capossele approved these changes

2021-07-28 12:28 UTC, darcy-camargo requested changes
What is her is really good, I would add some lines about the risks and care on using Manual Peering instead of Autopeering (since Autopeering is not mandatory it seems)

2021-07-28 18:16 UTC, oliviasaa commented on 3.5 Manual Peering.md
> +Manual peering can be additional protection against eclipse attacks as the manual peering is completely in the hands of the node operator based on real-world trust. Furthermore, it allows operating n
```suggestion
Manual peering can be an additional protection against eclipse attacks as the manual peering is completely in the hands of the node operator based on real-world trust. Furthermore, it allows operating nodes without exposing their IP addresses to the network.
```

2021-07-28 18:29 UTC, oliviasaa approved these changes
I left a suggestion in the 1st paragraph, but it's fine anyway :)

2021-08-10 18:32 UTC, darcy-camargo approved these changes

2021-08-12 17:31 UTC, merged