Docs - Improve SEO
iotaledger/IOTA-2.0-Research-Specifications pull request #99
Opened 2021-09-13 07:34 UTC by lucas-tortora

# Description of change

* Added keywords, image and description meta tags to all docs
* Renamed and moved docs files for browser friendly descriptive urls
* Fixed typos
* Fixed title capitalization
* Hosting images locally
* Updated links to wiki

## Links to any relevant issues

* Resolves  iotaledger/docs.iota.org#38

## Type of change

- [x] Enhancement (a non-breaking change which adds functionality)
- [x] Documentation Fix

## How the change has been tested

Docs site was built and served locally using node 12.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

2021-09-13 07:35 UTC, lucas-tortora commented
@iotaledger/tech-writers  could someone review this ?

2021-09-13 08:21 UTC, huhn511 approved these changes
LGTM! 👍

2021-09-15 11:37 UTC, apenzk approved these changes

2021-09-15 20:45 UTC, aleksei-korolev requested changes

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/1.1Introduction.md
> +These specifications are for a research prototype and are a work in progress, thus they may change.  Please refer to the preface for a description of their exact status.
```suggestion
These specifications are in progress and describe a research prototype. They will change — refer to the preface for updates.
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/2.3StandardPayloadsLayout.md
> +description: Payloads may recursively contain other payloads, that enables the creation of higher-level protocols based on the same concepts of layers, as in traditional software and network architec
```suggestion
description: This page describes the Standard Payloads Layout and different types of payloads that it includes.
```

Btw, I suggest my changes assuming that this is a description of what you find inside the page, not description of the page's subject.

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/3.3PeerDiscovery.md
> +description: This section defines the Peer Discovery protocol used to expose an interface providing a list of all the verified peers, its logic and the different requests and responses exchanged.
```suggestion
description: This section defines the Peer Discovery protocol that you use to receive a list of verified peers. Here we explain how it works and what kind of requests and responses you could use.
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/3.4NeighborSelection.md
> +description: In order for the network to work efficiently and for the nodes to be kept up-to-date about the ledger state, nodes exchange information with each other. Each node establishes a communica
```suggestion
description: This page explains how nodes find their neighbors and connect to them, a process that we call "peering". It allows nodes work efficiently without disrupting the actual ledger state.
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/4.2Timestamps.md
> +description: While online nodes may leverage FPC to vote on timestamps, nodes that join the network at a later time use an approach based on the approval weight to determine the validity of timestamp
```suggestion
description: Timestamps is a tool that allows nodes to keep track of time and agree on the age of the messages. We combine synchronious and asynchronious approaches. While online nodes vote on timestamps to achieve consensus, nodes that join the network later use approval weights.
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/4.3TipSelectionAlgorithm.md
> +description: The tip selection algorithm is the method by which messages are selected for approval by other issued messages joining the network. It allows the Tangle to grow in a stable and secure wa
```suggestion
description: The tip selection algorithm picks messages for approval by messages that join the network later. It allows the Tangle to grow in a stable and secure way, with quick approval and finality times.
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/4.5RateControl.md
> +description: In order to enable the machine-to-machine economy, IOTA does not allow either mining race nor fees, which makes an explicit rate control mechanism necessary to act as an emergency br dur
```suggestion
description: IOTA has no mining races or fees. To protect itself against spam attacks, Tangle has a rate control mechanism that could slow down the rate of messages from malicious nodes.

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/4.6CongestionControl.md
> +description: test
Bruh.

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/5.2LedgerState.md
> +description: The Realities Ledger State deals with double spends and leverages on certain properties of UTXO.
```suggestion
description: The Realities Ledger State prevents double spending by leveraging certain properties of UTXO.  
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/5.2LedgerState.md
> +- transactions
```suggestion
- transactions
- double spending
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/5.3Mana.md
> +description: This section introduces  *access Mana* and *consensus Mana* and determines which modules use each of these two types of Mana.
```suggestion
description: This section introduces  *access Mana* and *consensus Mana* and explains which modules use which Mana. 
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/6.1ObjectsOfConsensus.md
> +image: FPC is a binary voting protocol where each node starts with an initial opinion (a nulled boolean) on an objec. This specification describes how this binary voting protocol interacts with the r
.

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/6.3FastProbabilisticConsensus.md
> +description: Probabilistic Consensus (FPC), is triggered if the eligibility of a  message or transaction object is uncertain.
```suggestion
description: Fast Probabilistic Consensus (FPC) checks if a message or a transaction is eligible when it is not yet certain.
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/6.4Finalization.md
> +-
```suggestion
```

2021-09-15 20:45 UTC, aleksei-korolev commented on docs/6.5dRNG.md
> +description: asd
.

2021-09-28 11:56 UTC, aleksei-korolev approved these changes

2021-09-28 11:56 UTC, aleksei-korolev commented on docs/6.5dRNG.md
> +description: The Distributed Random Number Generator protocol is divided into three phases -  Committee selection, DKG and publication.
```suggestion
description: The Distributed Random Number Generator protocol is divided into three phases — committee selection, DKG and publication. 
```

2021-09-29 07:10 UTC, merged